services:
  - type: web
    name: nasa-earth-change
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python mexico_interactive_map.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: OPENAQ_API_KEY
        sync: false
      - key: NASA_FIRMS_API_KEY
        sync: false